listen:
    - 127.0.0.1:8888
allow:
    - 192.168.0.1

proxies:
   - name: noproxy
     type: direct

   - name: coorp_proxy
     type: ntlm
     user: bubnov
     domain: DOMAIN
     passhash: D9DB1BEAFC02ED1AC61205352FD06CB7 
     url: "proxy.example.com:8080"

   - name: http_proxy
     type: http
     user: bubnov
     password: "mypass@rd" 
     url: "http.example.com:8080"
     test: "xxx"

   - name: secret_proxy
     type: socks
     url: "proxy.example.com:8080"

autoconfig_url: ""

rules:
  noproxy:
    - "127.0.0.1"
  coorp_proxy:
    - "!google.com"
  http_proxy:
    - "google.com"
  secret_proxy:
    - "*"

